# Librerías

In [1]:
########## librerías a utilizar ##########

#Se importan la librerías a utilizar
import numpy as np
import pandas as pd

# Importar datos

In [3]:
########## Importando la data ##########

#Importar los datos de los archivos .csv almacenados en PC
#df_test = pd.read_csv('titanic_test.csv')
#df_train = pd.read_csv('titanic_train.csv')

#print(df_test.head())
#print(df_train.head())

# Colaboratory
# Montar Google Drive
##from google.colab import drive
##drive.mount('/content/drive')

# Ruta del archivo CSV
test_path = 'data/titanic_test.csv'
train_path = "data/titanic_train.csv"

# Leer el archivo CSV
df_test = pd.read_csv(test_path)
df_train = pd.read_csv(train_path)

print(df_test.head())
print(df_train.head())

  PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0  892,3,"Kelly, Mr. James",male,34.5,0,0,330911,...
1  893,3,"Wilkes, Mrs. James (Ellen Needs)",femal...
2  894,2,"Myles, Mr. Thomas Francis",male,62,0,0,...
3  895,3,"Wirz, Mr. Albert",male,27,0,0,315154,8....
4  896,3,"Hirvonen, Mrs. Alexander (Helga E Lindq...
  PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0  1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/...
1  2,1,1,"Cumings, Mrs. John Bradley (Florence Br...
2  3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,S...
3  4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May ...
4  5,0,3,"Allen, Mr. William Henry",male,35,0,0,3...

# Entendimiento de datos

In [4]:
########## Entendimiento de la data ##########

#Verifica la cantidad de datos que hay en los dataset
print('Cantidad de datos:')
print(df_train.shape)
print(df_test.shape)

#Verifica el tipo de datos contenida en ambos dataset
print('Tipos de datos:')
print(df_train.info())
print(df_test.info())

#Verifica los datos faltantes de los dataset
print('Datos faltantes:')
print(pd.isnull(df_train).sum())
print(pd.isnull(df_test).sum())

#Verifica las estadísticas básicas del dataset
print('Estadísticas del dataset:')
print(df_train.describe())
print(df_test.describe())

Cantidad de datos:
(891, 1)
(418, 1)
Tipos de datos:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 1 columns):
 #   Column                                                                           Non-Null Count  Dtype
---  ------                                                                           --------------  -----
 0   PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked  891 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 1 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked  418 non-null    object
dtypes: object(1)
memory usage: 3.4+ KB
None
Datos faltantes:
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked    0
dtype: int64
PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked    0
dtype: int64
Estadísticas del dataset:
       PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count                                                 891
unique                                                891
top     1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/...
freq                                                    1
       PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count                                                 418
unique                                                418
top     892,3,"Kelly, Mr. James",male,34.5,0,0,330911,...
freq                                                    1

# Preprocesamiento de datos

In [17]:
########## Preprocesamiento de la data ##########

# Transforma los datos de la variable sexo (categórico) en números
df_train['Sex'].replace(['female','male'],[0,1],inplace=True)
df_test['Sex'].replace(['female','male'],[0,1],inplace=True)

#Transforma los datos de embarque (categórico) en números
df_train['Embarked'].replace(['Q','S', 'C'],[0,1,2],inplace=True)
df_test['Embarked'].replace(['Q','S', 'C'],[0,1,2],inplace=True)

#Reemplazo los datos faltantes en la edad por la media de esta variable
print(df_train["Age"].mean())
print(df_test["Age"].mean())
promedio = 30
df_train['Age'] = df_train['Age'].replace(np.nan, promedio)
df_test['Age'] = df_test['Age'].replace(np.nan, promedio)

#Crea varios grupos/rangos de edades
#Rangos de edad: 0-8, 9-15, 16-18, 19-25, 26-40, 41-60, 61-100
bins = [0, 8, 15, 18, 25, 40, 60, 100]
names = ['1', '2', '3', '4', '5', '6', '7']
df_train['Age'] = pd.cut(df_train['Age'], bins, labels = names)
df_test['Age'] = pd.cut(df_test['Age'], bins, labels = names)

#Se elimina la columna de "Cabin" ya que tiene muchos datos perdidos
# El parámetro axis=1 indica que se deben eliminar columnas en lugar de filas (axis=0).
# El parámetro inplace indica si la operación se realiza directamente en el
# DataFrame original o devolvuelve una nueva copia con filas o columnas eliminadas.
df_train.drop(['Cabin'], axis = 1, inplace=True)
df_test.drop(['Cabin'], axis = 1, inplace=True)

#Elimina las columnas que se considera que no son necesarias para el analisis
df_train = df_train.drop(['PassengerId','Name','Ticket'], axis=1)
df_test = df_test.drop(['Name','Ticket'], axis=1)

#Se elimina las filas con datos perdidos

df_train.dropna(axis=0, how='any', inplace=True)
df_test.dropna(axis=0, how='any', inplace=True)

#Verifica los datos faltantes y tamaño
print(pd.isnull(df_train).sum())
print(pd.isnull(df_test).sum())

print(df_train.shape)
print(df_test.shape)

print(df_test.head())
print(df_train.head())

# Guardar el DataFrame en un archivo CSV
df_train.to_csv('/content/drive/MyDrive/Colab Notebooks/train_procesado.csv', index=False, sep=',', encoding='utf-8')

29.69911764705882
30.272590361445783
Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64
PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64
(889, 8)
(417, 8)
   PassengerId  Pclass  Sex Age  SibSp  Parch     Fare  Embarked
0          892       3    1   5      0      0   7.8292         0
1          893       3    0   6      1      0   7.0000         1
2          894       2    1   7      0      0   9.6875         0
3          895       3    1   5      0      0   8.6625         1
4          896       3    0   4      1      1  12.2875         1
   Survived  Pclass  Sex Age  SibSp  Parch     Fare  Embarked
0         0       3    1   4      1      0   7.2500       1.0
1         1       1    0   5      1      0  71.2833       2.0
2         1       3    0   5      0      0   7.9250       1.0
3         1       1    0   5      1      0  53.1000       1.0
4         0       3    1   5      0      0   8.0500       1.0